### ISSUE TITLE
Refusing connection

### ISSUE THREAD

**Issue by patilnikhilh80** [ashishdoneriya/influxdb-java#9]
I have installed Oracle Vbox and have Centos7 running in it. I have installed influx on centos. Now I am trying to access Influxdb from java web service(hosted on local tomcat server).
getting error as
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8086 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)

**Comment by ashishdoneriya** [comment]
Hi @patilnikhilh80 I think your influxdb  is not running. Check whether influxdb is up and running by going to its cli
`influx --port 8086`
If you get the error like
```
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.
```
then it means influxdb is not running.
You can check why influxdb is not running by checking its logs ( `/var/log/influxdb/influxdb.log`)
Most of the time influxdb fails to start because of a port `8088`that influxdb uses as it meta port which is already occupied in most of the system. You can change this port from its configuration file (influxdb.conf)
`bind-address = ":8088"`

and also make sure your port 8086 is also free because influxdb also uses that. If not free then change it in the configuration
